INSERT INTO `layouts` (`id`, `layoutname`, `layoutcreator`, `layoutdescription`, `layoutqpt`, `layoutpreview`, `byuser`, `istiny`, `issmall`, `ismedium`, `islarge`, `isscreen`, `popular`) VALUES
(1, 'Index map A4 Portrait', 'Klas Karlsson', 'Map with index grid', '../layouts/resources/5f2ea54ce442b5.33477222.qpt', '../layouts/images/5f2ea54ce44388.34804648.jpg', 'klakar', NULL, 1, NULL, NULL, NULL, NULL),
(2, 'Full HD screen with text area', 'Klas Karlsson', 'This layout has the resolution 1920x1080 and might be suitable for generating a presentation slide. It has a title placeholder and an area for some text.', '../layouts/resources/5f2ea5f98a53e1.56763458.qpt', '../layouts/images/5f2ea5f98a5464.63480178.jpg', 'klakar', NULL, NULL, NULL, NULL, 1, NULL),
(3, 'Standard A3 Landscape with grid', 'Klas Karlsson', 'Created in 1:50\'000 scale with 1 km grids suitable for UTM projections.\r\nA lot of map layout information in the margins, as well as a text area for additional information.', '../layouts/resources/5f2ea70884d101.74067897.qpt', '../layouts/images/5f2ea70884d192.51494044.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL),
(4, 'Standard A3 Portrait with grid', 'Klas Karlsson', 'Created in 1:50\'000 scale with 1 km grids suitable for UTM projections. A lot of map layout information in the margins, as well as a text area for additional information.', '../layouts/resources/5f2eae93174493.47577054.qpt', '../layouts/images/5f2eae93174540.49168187.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL),
(5, 'Drawing A1 Landscape - information bottom right', 'Klas Karlsson', 'This layout can be used in QGIS as a simple CAD drawing substitution. It has a simple information box in the bottom right. It is meant for extremely large scale maps and is default set to 1:400.', '../layouts/resources/5f2eafcd518c84.31834074.qpt', '../layouts/images/5f2eafcd518d27.51669229.png', 'klakar', NULL, NULL, NULL, 1, NULL, NULL),
(6, 'Postcard CSS Title', 'Klas Karlsson', ' Simple postcard with title styled with CSS. It is simplest to use the \"title\" variable in the layout to change the title text.', '../layouts/resources/5f2eb619e1eda7.23049489.qpt', '../layouts/images/5f2eb619e1ee50.29674482.png', 'klakar', 1, NULL, NULL, NULL, NULL, 1),
(7, 'Standard A4 Landscape with grid', 'Klas Karlsson', 'Created in 1:50\'000 as default, but with grids prepared for 1, 5 and 10 km interval, as well as 5 and 15 minutes lat/long. This orientation leaves room for some extra text to the right.', '../layouts/resources/5f2f99abe5c471.47526868.qpt', '../layouts/images/5f2f99abe5c4e0.37617526.jpg', 'klakar', NULL, 1, NULL, NULL, NULL, NULL),
(8, 'Standard A4 Portrait with grid', 'Klas Karlsson', 'Standard projected map layout with prepared grids with 1, 5 and 10 km interval, as well as 5 and 15 minutes lat/long. A lot of extra information about the map is placed in the margins. The map is default at 1:50\'000.', '../layouts/resources/5f2f9a8be01496.24803415.qpt', '../layouts/images/5f2f9a8be01522.74046234.jpg', 'klakar', NULL, 1, NULL, NULL, NULL, NULL),
(9, 'Instagram format 1:1', 'Klas Karlsson', 'This square layout is created to fit the Instagram 1080x1080 format. It is easy to change Title and Subtitle with variables in the layout settings.', '../layouts/resources/5f2f9ea669c487.31156090.qpt', '../layouts/images/5f2f9ea669c4f4.16900436.jpg', 'klakar', NULL, NULL, NULL, NULL, 1, NULL);

-- --------------------------------------------------------

--
-- Tabellstruktur `styles`
--

--
-- Dumpning av Data i tabell `styles`
--

INSERT INTO `styles` (`id`, `stylename`, `stylecreator`, `styledescription`, `stylexml`, `stylepreview`, `byuser`, `ismarker`, `isline`, `isfill`, `isramp`, `istext`, `islabel`, `ispatch`, `popular`) VALUES
(1, 'Panel', 'Klas Karlsson', ' Resembling old wood inlay panels in style. Easily change color, size and orientation.', 'styles/resources/panel.xml', 'styles/images/Screenshot from 2020-07-15 18-22-05.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(2, 'Dormido Rough Circles', 'Klas Karlsson', '  SVG style based on Hannah Dormido hand drawn map style with circles. You can easily change colors, size and orientation for the pattern.', 'styles/resources/dormido_rough.xml', 'styles/images/Screenshot from 2020-07-16 10-12-36.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, 1),
(3, 'Barb Wire', 'Klas Karlsson', '  SVG marker line style.', 'styles/resources/barb_wire.xml', 'styles/images/Screenshot from 2020-07-21 15-34-02.png', 'klakar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'Cubes Pattern', 'Klas Karlsson', ' Pattern of symetric cubes. Style can be changed by color, size and orientation with ease.', 'styles/resources/cubes.xml', 'styles/images/Screenshot from 2020-07-15 15-09-48.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(11, 'Denim Textile', 'Klas Karlsson', ' This SVG fill have a textile texture. With the default fill color it can resemble denim. Other colors and changing the size and orientation, will give other texture appearance.', 'styles/resources/denim.xml', 'styles/images/denim.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(6, 'Measure', 'Klas Karlsson', ' Simple style that puts measurement on all polygon segments. The layer need to be in a projected coordinatesystem with either \"meters\" or \"feet\" as unit of measurement.', 'styles/resources/Measure.xml', 'styles/images/Screenshot from 2020-08-01 20-33-49.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(7, 'Mattress', 'Klas Karlsson', ' Simple SVG marker fill style that resembles a mattress or upholstered furniture.', 'styles/resources/mattress.xml', 'styles/images/Screenshot from 2020-07-18 11-11-17.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(9, 'Cross Stitch Pattern', 'Klas Karlsson', ' Repeating SVG marker fill resembling cross stitch. Easily change color with the basic fill color.', 'styles/resources/cross_stitch.xml', 'styles/images/Screenshot from 2020-07-15 10-58-42.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(10, 'Rock Crystals', 'Klas Karlsson', ' Random fill style with small color variations from the selected base color. Also some \"star\" highlights in a random pattern.', 'styles/resources/rock_crystal.xml', 'styles/images/Screenshot from 2020-07-20 14-09-41.png', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(12, 'Organic Blocks', 'Klas Karlsson', ' Organic blocks with a slight variation in the pattern. Change base color with ease, and pattern size and orientation in the SVG fill settings.', 'styles/resources/organic_blocks.xml', 'styles/images/organic_blocks.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(13, '70s Wallpaper', 'Klas Karlsson', ' This is a point pattern fill, with ellipse markers with random sizes. It gives an impression of a wallpaper pattern found in a lot of homes in the 70s. Change the base fill color, and the pattern will adapt.', 'styles/resources/70s_wallpaper.xml', 'styles/images/wallpaper-70s.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(14, 'Cool Water Fill', 'Klas Karlsson', ' This is a mix of shapeburst fill and SVG fill. Changing base fill color will change all parts of the style in color accordingly.', 'styles/resources/Cool_Water_Area.xml', 'styles/images/cool_lakes_pattern.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(15, 'Zipper line pattern', 'Klas Karlsson', '  A simple repeating line pattern that resembles a zipper.', 'styles/resources/zipper.xml', 'styles/images/Screenshot from 2020-08-03 18-46-42.png', 'klakar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'Sharpie', 'Klas Karlsson', ' Exaggerated line style that may or may not look like a (badly drawn) sharpie line.', 'styles/resources/Sharpie.xml', 'styles/images/sharpie.png', 'klakar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'Pencil', 'Klas Karlsson', ' One of many variations on the pencil style. This is one of the simpler, but it can be effective in the right place.', 'styles/resources/Pencil.xml', 'styles/images/pencil.png', 'klakar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Pen (ballpoint)', 'Klas Karlsson', '  Line style created to look like it was drawn with a ballpoint pen.', 'styles/resources/ballpoint_pen.xml', 'styles/images/pen.png', 'klakar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'CAD Revision Cloud', 'Jon Orchard', 'A CAD-inspired revision cloud line style.', 'styles/resources/CAD Revision cloud.xml', 'styles/images/Revision.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'Fantasia', 'Klas Karlsson', 'Random fill-style where you set the \"tone\" of the style by color and opacity. If you drill down into the style settings it is easy to change size and resolution.', '../styles/resources/5f2ac8e2140216.09033704.xml', '../styles/images/5f2ac8e21402a4.97545666.jpg', 'klakar', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(21, 'Blue Cheese', 'Romain Lx', '  A small taste of France with this typical blue cheese mould style.\r\n\r\n2 shapeburst fill + 1 inverted polygons (with geometry generator) if you need to find a nice cheesy colour.\r\nMaybe inadequate for datasets with large number of polygons', '../styles/resources/5f2b028244e4f1.91634423.xml', '../styles/images/5f2b028244e595.02806186.png', 'lacxrx', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(25, 'Brazil\'s States -  Limite dos estados do Brasil', 'HermÃ­nio Sabino de Oliveira Junior', 'Styles of all federative units in Brazil.\r\nThe state division of Brazil', '../styles/resources/5f2dd3fe2130e3.56895725.xml', '../styles/images/5f2dd3fe213194.63332282.jpg', 'herminiosabino', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
(23, 'Cultivo de frijol', 'Carlos R.', '   Polygon fill for beans crops.\r\nIconos diseÃ±ados por Vitaly Gorbachev', '../styles/resources/5f2b33ee30f9d4.93708272.xml', '../styles/images/5f2b33ee30fa63.26828068.jpeg', 'carlosgis', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL),
(24, 'Legend Patches Basic Pack', 'Klas Karlsson', 'A set of basic legend patches for you to use in your QGIS layout legends.', '../styles/resources/5f2c31183d6119.64859341.xml', '../styles/images/5f2c31183d61c6.77483439.png', 'klakar', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL),
(27, 'Italian regions (Regioni Italiane)', 'TotÃ² Fiandaca', ' These are the twenty Italian regions to be used as Legend Patch shapes', '../styles/resources/5f2ec31ea091c2.42912362.xml', '../styles/images/5f2ec31ea09265.72627163.png', 'pigreco', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL);


